#!/usr/bin/env bash
# Task 3
# updating and installing
sudo apt-get -y update
sudo apt-get -y install nginx

# adding firewall
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page with a string
echo "Hello World!" | sudo tee /var/www/html/index.html

# Checking configurations for Syntax errors
sudo nginx -t

# Restarting nginx service
sudo service nginx restart

lines="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

if  ! grep -q -e "redirect_me" /etc/nginx/sites-available/default 
then
    sed -i "s|server_name _;|server_name _;${lines}|g" /etc/nginx/sites-available/default
    sudo service nginx restart
fi
