#!/usr/bin/env bash
# Print FizzBuzz algorithm from 1 - 100
number=1
for (( number=0; number <= 100; number++))
do
    if (( number % 15 == 0))
    then
        echo "FizzBuzz"
    elif (( number % 3 == 0))
    then
        echo "Fizz"
    elif (( number % 5 == 0))
    then
        echo "Buzz"
    else 
        echo $number
    fi
done