#!/usr/bin/env bash
# Print based on readme
# Holds current iteration
count=1
while [ $count -ne 11 ]; do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done
