#!/usr/bin/env bash
#  displays the time for 12 hours and 59 minutes
hour=0
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    seconds=1
    while [ $seconds -le 59 ]; do
        echo "$seconds"
        ((seconds++))
    done
    ((hour++))
done
