#!/usr/bin/env bash
# Task 0
# Install ufw
sudo apt-get update
sudo apt-get install -y ufw
# Allow ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
# Enable ufw
sudo ufw enable