#!/usr/bin/env bash
# Task 0
# Add facebook

if ! grep -q "facebook" /etc/hosts
then
    echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
fi
# Change localhost
if  ! grep -q '127.0.0.2' /etc/hosts
then
    cp /etc/hosts ~/hosts.new
    sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
    cp -f ~/hosts.new /etc/hosts
fi