#!/usr/bin/env bash
# Task 0
# Add facebook

if [ -z "$(cat /etc/hosts | grep facebook)" ]
then
    echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
fi
# Change localhost
if [ -z "$(cat /etc/hosts | grep '127.0.0.2')" ]
then
    cp /etc/hosts ~/hosts.new
    sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
    cp -f ~/hosts.new /etc/hosts
fi